# Generated by Django 5.2.8 on 2025-11-26 20:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyzedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("task_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                ("urgency", models.FloatField()),
                ("importance", models.FloatField()),
                ("effort", models.FloatField()),
                ("dependency", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
