# Generated by Django 5.2.8 on 2025-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzedtask",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
