# Generated by Django 5.2.8 on 2025-11-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0002_analyzedtask_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnedWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_urgency", models.FloatField(default=0.4)),
                ("default_importance", models.FloatField(default=0.3)),
                ("default_effort", models.FloatField(default=0.2)),
                ("default_dependency", models.FloatField(default=0.1)),
                ("urgency", models.FloatField(default=0.4)),
                ("importance", models.FloatField(default=0.3)),
                ("effort", models.FloatField(default=0.2)),
                ("dependency", models.FloatField(default=0.1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
