# Generated by Django 5.2.8 on 2025-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0003_learnedweights"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=100)),
                ("was_helpful", models.BooleanField()),
                ("urgency", models.FloatField(default=0)),
                ("importance", models.FloatField(default=0)),
                ("effort", models.FloatField(default=0)),
                ("dependency", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_urgency", models.FloatField(default=0.4)),
                ("default_importance", models.FloatField(default=0.3)),
                ("default_effort", models.FloatField(default=0.2)),
                ("default_dependency", models.FloatField(default=0.1)),
                ("weight_urgency", models.FloatField(default=0.4)),
                ("weight_importance", models.FloatField(default=0.3)),
                ("weight_effort", models.FloatField(default=0.2)),
                ("weight_dependency", models.FloatField(default=0.1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="LearnedWeights",
        ),
    ]
